### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PODAMEKALAPREETHI** [pinetr2e/napkin#10]
I am running this codes in python 3.8 and I install napkin 0.6.4. Even though I am getting error like 
for group: AttributeError: 'Context' object has no attribute 'group'
for helper: AttributeError: module 'helper' has no attribute 'generate_markdown_file'

**Comment by pinetr2e** [comment]
You need to upgrade Napkin.(pip install --upgrade napkin)
The version 0.6.4 is the old version before the change you asked.
