### ISSUE TITLE
Can we generate png from puml in offline?

### ISSUE THREAD

**Issue by PODAMEKALAPREETHI** [pinetr2e/napkin#11]

**Comment by pinetr2e** [comment]
You can run plantuml server locally then specify the local URL when running napkin.

For example, start a server with default port:
 $ java -jar plantuml.jar -picoweb

Then, you can run napkin like the following:
 $ napkin demo_hello_world.py -f plantuml_png --server-url=http://localhost:8080

Please check https://plantuml.com/picoweb
