### ISSUE TITLE
Simple Style Incorporation

### ISSUE THREAD

**Issue by nathanvercaemert** [pinetr2e/napkin#14]
Maybe I'm just missing something simple, but I can't find a way to include basic changes to the styles. I'm talking about something like:

```
skinparam monochrome true
```

at the top of the puml output under @startuml. Does it already exist? Cool program by the way!

**Comment by pinetr2e** [comment]
At the moment, there is no such customization support.
It will be useful to add some "hook".  For example, it can be a simple command line option to specify the file or string to prepend right after @startuml.  

Please feel free to implement it.

**Comment by nathanvercaemert** [comment]
I'm on it. I'm going to call it "--global-style" (unless you specify otherwise) with the idea that someday I'll get around to implementing styles with smaller scope as well.

**Comment by pinetr2e** [comment]
With version 0.6.9, a new command line option '--raw-header-file' or '-H' was added to specify file containing text to prepend right after @startuml.

A new interface, c.raw_header() can be also used from script level.  Please check https://github.com/pinetr2e/napkin/blob/master/DEMO_EXAMPLES.md#raw-header
