### ISSUE TITLE
Napkin(note)

### ISSUE THREAD

**Issue by PODAMEKALAPREETHI** [pinetr2e/napkin#4]
Hi,can we change the note to left or right using napkin?

**Comment by pinetr2e** [comment]
That will be useful. 

Instead of left or right, it will be more natural to use 'callee/caller', which decides left/right depending on call direction.

Please check the latest version.
Cheers ~

**Comment by PODAMEKALAPREETHI** [comment]
Thank you.

**Comment by PODAMEKALAPREETHI** [comment]
How to do group for certain req and resp using python code in napkin?
