### ISSUE TITLE
Napkin(Heading)

### ISSUE THREAD

**Issue by preethiiii** [pinetr2e/napkin#8]
Can we give headings like this?
       ========Hello==========

**Comment by pinetr2e** [comment]
Do you mean something which will output 'divider' in PlantUML? 
(https://plantuml.com/sequence-diagram#2908050e771fb91a)

As Napkin only supports PlantUML as the only backend at the moment, it will be better for you to ask something like, 'How can we generate XXX in PlantUML using Napkin'.

**Comment by pinetr2e** [comment]
Please check the latest version again.

https://github.com/pinetr2e/napkin/blob/master/DEMO_EXAMPLES.md#devider
